/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./templates/**/*.html", "./accounts/**/*.html"],
  theme: {
    extend: {
      colors: {
        background: "#f9f9fc",
        "surface-container-high": "#e8e8ea",
        surface: "#f9f9fc",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e9c400",
        "surface-variant": "#e2e2e5",
        "on-surface-variant": "#434653",
        "on-secondary-container": "#705e00",
        "on-secondary-fixed": "#221b00",
        "primary-container": "#0045b1",
        "tertiary-container": "#9f0014",
        "secondary-container": "#fed721",
        "on-primary-fixed-variant": "#003fa4",
        "on-tertiary-container": "#ffa7a0",
        "inverse-on-surface": "#f0f0f3",
        secondary: "#705d00",
        "tertiary-fixed": "#ffdad6",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#410003",
        "on-background": "#1a1c1e",
        outline: "#737684",
        "secondary-fixed": "#ffe16d",
        "primary-fixed-dim": "#b3c5ff",
        "surface-tint": "#2558c3",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f3f6",
        "surface-container-highest": "#e2e2e5",
        "inverse-primary": "#b3c5ff",
        "on-surface": "#1a1c1e",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container": "#eeeef0",
        "primary-fixed": "#dae1ff",
        "on-secondary": "#ffffff",
        primary: "#003081",
        "surface-dim": "#dadadc",
        "on-primary-container": "#a7bdff",
        "inverse-surface": "#2f3133",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9fc",
        "surface-container-lowest": "#ffffff",
        tertiary: "#74000b",
        "on-tertiary-fixed-variant": "#930011",
        "outline-variant": "#c3c6d5",
        "on-primary-fixed": "#001849",
        "on-secondary-fixed-variant": "#544600",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "0.75rem",
        xl: "0.75rem",
        "2xl": "0.75rem",
        "3xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Outfit", "system-ui", "sans-serif"],
        body: ["Outfit", "system-ui", "sans-serif"],
        label: ["Outfit", "system-ui", "sans-serif"],
        procedure: ["Outfit", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
