# Generated by Django 6.0.3 on 2026-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_examen', 'En examen'), ('approuve', 'Approuvé'), ('action_requise', 'Action requise'), ('rejete', 'Rejeté')], db_index=True, default='brouillon', max_length=32)),
                ('declarant_nom', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom et prénom(s)')),
                ('declarant_telephone', models.CharField(blank=True, default='', max_length=40, verbose_name='Téléphone')),
                ('declarant_email', models.CharField(blank=True, default='', max_length=254, verbose_name='Email de contact')),
                ('declarant_adresse', models.TextField(blank=True, default='', verbose_name='Adresse complète')),
                ('motif_precisions', models.TextField(blank=True, default='', verbose_name='Motif et précisions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_demande',
                'ordering': ('-updated_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_document',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('title', models.CharField(blank=True, default='', max_length=180, verbose_name='Titre (court)')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='Texte (long)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_galleryphoto',
                'ordering': ('sort_order', '-created_at'),
                'managed': False,
            },
        ),
    ]
