# Generated by Django 6.0.3 on 2026-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
