# Generated by Django 6.0.3 on 2026-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='declarant_adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='demande',
            name='declarant_email',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='demande',
            name='declarant_nom',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom et prénom(s)'),
        ),
        migrations.AddField(
            model_name='demande',
            name='declarant_telephone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='demande',
            name='motif_precisions',
            field=models.TextField(blank=True, default='', verbose_name='Motif et précisions'),
        ),
    ]
