# Generated by Django 6.0.3 on 2026-04-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_demande_declarant_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_user_id_457002_idx',
            old_name='accounts_pa_user_id_2fb7cf_idx',
        ),
    ]
