# Generated by Django 6.0.3 on 2026-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_galleryphoto_commune_adresse_commune_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='fuseau_horaire',
            field=models.CharField(blank=True, default='Africa/Kinshasa', max_length=64),
        ),
        migrations.AddField(
            model_name='commune',
            name='langue_defaut',
            field=models.CharField(blank=True, default='fr', max_length=32),
        ),
        migrations.AddField(
            model_name='commune',
            name='nombre_quartiers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='population_estimee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='quartier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='commune',
            name='services_estimes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
