# Generated by Django 6.0.3 on 2026-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_commune_fuseau_horaire_commune_langue_defaut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryphoto",
            name="title",
            field=models.CharField(blank=True, default="", max_length=180, verbose_name="Titre (court)"),
        ),
        migrations.AddField(
            model_name="galleryphoto",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Texte (long)"),
        ),
        migrations.RunSQL(
            sql="UPDATE accounts_galleryphoto SET title = caption WHERE (title = '' OR title IS NULL);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='caption',
        ),
    ]
