# Generated by Django 6.0.3 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_galleryphoto_caption_galleryphoto_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryphoto",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Texte (long)",
            ),
        ),
    ]
