# Generated by Django 6.0.3 on 2026-04-25 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_galleryphoto_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140, unique=True)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.commune'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super-admin (Ministère)'), ('city_admin', 'Admin ville (Hôtel de ville)'), ('commune_admin', 'Admin commune (Bourgmestre)'), ('citoyen', 'Citoyen'), ('agent', 'Agent'), ('chef_service', 'Chef de service'), ('admin', 'Admin (legacy)')], default='citoyen', max_length=32),
        ),
        migrations.AddField(
            model_name='commune',
            name='ville_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='accounts.ville'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.ville'),
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('ville_parent', 'nom'), name='uq_commune_ville_nom'),
        ),
    ]
