# Generated by Django 6.0.3 on 2026-04-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ville_userprofile_commune_alter_commune_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneTaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('ipm', 'IPM'), ('irl', 'IRL'), ('etalage', 'Taxe d’étalage')], db_index=True, max_length=24)),
                ('channel', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Banque')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('succeeded', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='succeeded', max_length=24)),
                ('amount_cdf', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to='accounts.commune')),
            ],
            options={
                'ordering': ('-paid_at',),
                'indexes': [models.Index(fields=['commune', 'tax_type', 'paid_at'], name='accounts_co_commune_266ae9_idx'), models.Index(fields=['commune', 'channel', 'paid_at'], name='accounts_co_commune_4366fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('asbl', 'ASBL'), ('church', 'Église')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='accounts.commune')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['commune', 'entity_type', 'created_at'], name='accounts_le_commune_3c48dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('erosion', 'Érosion'), ('flood', 'Inondation'), ('landslide', 'Glissement'), ('other', 'Autre')], db_index=True, max_length=24)),
                ('level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('identified_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_zones', to='accounts.commune')),
            ],
            options={
                'ordering': ('-identified_at',),
                'indexes': [models.Index(fields=['commune', 'risk_type', 'identified_at'], name='accounts_ri_commune_59be55_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('public_order', 'Ordre public'), ('crime', 'Criminalité'), ('disaster', 'Catastrophe'), ('other', 'Autre')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], db_index=True, max_length=24)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='accounts.commune')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['commune', 'occurred_at'], name='accounts_se_commune_07b621_idx'), models.Index(fields=['commune', 'incident_type', 'occurred_at'], name='accounts_se_commune_b8562d_idx')],
            },
        ),
    ]
