# Generated by Django 6.0.3 on 2026-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='chef_lieu',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='province',
            name='desserte_agricole',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='province',
            name='etat_batiments_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='province',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='limites_voisines',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='province',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='nb_territoires',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='nb_villes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='population_estimee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='recettes_prevues_cdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='reseau_routier',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='province',
            name='ressources_principales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='province',
            name='superficie_km2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
