# Generated by Django 6.0.3 on 2026-04-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_province_chef_lieu_province_desserte_agricole_and_more'),
        ('referentiel_geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commune',
            name='uq_commune_ville_nom',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='referentiel_geo.commune'),
        ),
        migrations.RemoveIndex(
            model_name='communetaxpayment',
            name='accounts_co_commune_266ae9_idx',
        ),
        migrations.RemoveIndex(
            model_name='communetaxpayment',
            name='accounts_co_commune_4366fc_idx',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='citoyen',
        ),
        migrations.RemoveField(
            model_name='document',
            name='demande',
        ),
        migrations.DeleteModel(
            name='GalleryPhoto',
        ),
        migrations.RemoveIndex(
            model_name='legalentity',
            name='accounts_le_commune_3c48dc_idx',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.RemoveIndex(
            model_name='riskzone',
            name='accounts_ri_commune_59be55_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityincident',
            name='accounts_se_commune_07b621_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityincident',
            name='accounts_se_commune_b8562d_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='referentiel_geo.ville'),
        ),
        migrations.RemoveField(
            model_name='commune',
            name='ville_parent',
        ),
        migrations.RemoveField(
            model_name='communetaxpayment',
            name='commune',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='riskzone',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='securityincident',
            name='commune',
        ),
        migrations.DeleteModel(
            name='Ville',
        ),
        migrations.DeleteModel(
            name='CommuneTaxPayment',
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
        migrations.DeleteModel(
            name='RiskZone',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='SecurityIncident',
        ),
    ]
