# Generated by Django 6.0.3 on 2026-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('quartier', models.CharField(blank=True, default='', max_length=120)),
                ('ville', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('services_estimes', models.PositiveIntegerField(blank=True, null=True)),
                ('population_estimee', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_quartiers', models.PositiveIntegerField(blank=True, null=True)),
                ('langue_defaut', models.CharField(blank=True, default='fr', max_length=32)),
                ('fuseau_horaire', models.CharField(blank=True, default='Africa/Kinshasa', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_commune',
                'ordering': ('nom',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('chef_lieu', models.CharField(blank=True, default='', max_length=140)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('limites_voisines', models.TextField(blank=True, default='')),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('population_estimee', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_territoires', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_villes', models.PositiveIntegerField(blank=True, null=True)),
                ('ressources_principales', models.TextField(blank=True, default='')),
                ('recettes_prevues_cdf', models.PositiveIntegerField(blank=True, null=True)),
                ('etat_batiments_admin', models.TextField(blank=True, default='')),
                ('reseau_routier', models.TextField(blank=True, default='')),
                ('desserte_agricole', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_province',
                'ordering': ('nom',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140, unique=True)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_ville',
                'ordering': ('nom',),
                'managed': False,
            },
        ),
    ]
