# Generated by Django 6.0.3 on 2026-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneTaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('ipm', 'IPM'), ('irl', 'IRL'), ('etalage', 'Taxe d’étalage')], db_index=True, max_length=24)),
                ('channel', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Banque')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('succeeded', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='succeeded', max_length=24)),
                ('amount_cdf', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_communetaxpayment',
                'ordering': ('-paid_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('asbl', 'ASBL'), ('church', 'Église')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_legalentity',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('erosion', 'Érosion'), ('flood', 'Inondation'), ('landslide', 'Glissement'), ('other', 'Autre')], db_index=True, max_length=24)),
                ('level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('identified_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_riskzone',
                'ordering': ('-identified_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('public_order', 'Ordre public'), ('crime', 'Criminalité'), ('disaster', 'Catastrophe'), ('other', 'Autre')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], db_index=True, max_length=24)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_securityincident',
                'ordering': ('-occurred_at',),
                'managed': False,
            },
        ),
    ]
