"""
Django settings for sisepcommune project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (local dev) without extra dependency
_env_file = BASE_DIR / ".env"
if _env_file.exists():
    for raw in _env_file.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        v = v.strip().strip('"').strip("'")
        if k and k not in os.environ:
            os.environ[k] = v


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_insecure_dev_secret_key = "django-insecure-@fndzes$dpqwc1#+u7#)ecf9sx!ztcc%8-s_&%8bf#5(+h)z!m"
SECRET_KEY = (os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY") or _insecure_dev_secret_key).strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Hôtes autorisés : en production, liste obligatoire (ex. ALLOWED_HOSTS=portail.ville.cd,www.portail.ville.cd)
_hosts_raw = (os.environ.get("ALLOWED_HOSTS") or "").strip()
ALLOWED_HOSTS = [h.strip() for h in _hosts_raw.split(",") if h.strip()]

LOGIN_URL = "/login/"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dossiers',
    'gouvernance',
    'referentiel_geo',
    'accounts.apps.AccountsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'sisepcommune.middleware.StripPublicAuthMessagesForHdvMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'sisepcommune.middleware.SensitiveHtmlNoCacheMiddleware',
]

ROOT_URLCONF = 'sisepcommune.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sisepcommune.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.environ.get("DB_ENGINE", "mysql").lower()
if DB_ENGINE in {"mysql", "mariadb"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DB_NAME", "commune"),
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cache (utilisé pour la limitation de débit, etc.)
# En production, remplacez par Redis/Memcached si besoin.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "sisepcommune-default",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("fr", "Français"),
    ("ln", "Lingála"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Static assets stored at project root (ex: images/logo-white.png)
STATICFILES_DIRS = [
    BASE_DIR / 'images',
    BASE_DIR / 'static',
]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Uploads (images) require Pillow in your environment.

# Email (SMTP) — use environment variables (do not hardcode secrets)
# In this project we ALWAYS send real emails via SMTP.
EMAIL_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("SMTP_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("SMTP_USE_TLS", "1") == "1"
EMAIL_HOST_USER = os.environ.get("SMTP_USERNAME", "")
EMAIL_HOST_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@localhost")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

_is_server_command = any(arg in {"runserver", "gunicorn", "uvicorn"} for arg in sys.argv)

if not DEBUG:
    if SECRET_KEY == _insecure_dev_secret_key:
        raise ImproperlyConfigured(
            "SECRET_KEY : définissez DJANGO_SECRET_KEY (ou SECRET_KEY) avec une valeur aléatoire longue "
            "lorsque DEBUG=False."
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS : définissez au moins un nom d’hôte (séparés par des virgules) lorsque DEBUG=False."
        )

if _is_server_command and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    raise RuntimeError(
        "Configuration SMTP manquante. Définissez SMTP_USERNAME et SMTP_PASSWORD "
        "(mot de passe d'application Gmail) avant de démarrer le serveur."
    )

# --- Compte Ministère de l’Intérieur (super-administrateur national) ---
# Ces valeurs peuvent être définies dans le fichier .env.
MINISTER_ADMIN_USERNAME = os.environ.get("MINISTER_ADMIN_USERNAME", "ministere")
MINISTER_ADMIN_EMAIL = os.environ.get("MINISTER_ADMIN_EMAIL", "ministere@muniworks.local")
MINISTER_ADMIN_PASSWORD = os.environ.get("MINISTER_ADMIN_PASSWORD", "")
if DEBUG and not MINISTER_ADMIN_PASSWORD:
    # Valeur dev par défaut (à changer dans .env)
    MINISTER_ADMIN_PASSWORD = "ministere12345"
if (not DEBUG) and _is_server_command and not MINISTER_ADMIN_PASSWORD:
    raise RuntimeError("MINISTER_ADMIN_PASSWORD manquant. Définissez-le avant de démarrer le serveur.")

# --- Statistiques (Hôtel de ville) ---
# Les recettes / taxes affichées au dashboard sont des estimations basées sur des tarifs simples.
# Mettez ces valeurs dans .env pour activer les KPIs financiers.
HDV_CURRENCY = os.environ.get("HDV_CURRENCY", "CDF")
HDV_FEE_DOCUMENT = int(os.environ.get("HDV_FEE_DOCUMENT", "0"))  # ex: 5000
HDV_FEE_OCCUPATION = int(os.environ.get("HDV_FEE_OCCUPATION", "0"))  # ex: 25000

# --- Cookies, HTTPS et HSTS (renforcés hors développement) ---
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in (os.environ.get("CSRF_TRUSTED_ORIGINS") or "").split(",")
    if o.strip()
]
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "1") == "1"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Derrière un reverse proxy TLS, décommenter et adapter :
    # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
